[project]
name = "example_project"
lang = "java"
version = "0.1.0"
main = "Main"

[toolchain]
java = "25"

[runtime]
vendor = "temurin"
version = "25"

[dependencies]
"com.google.code.gson:gson" = "2.10.1"